//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Web.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About System.
        /// </summary>
        internal static string AboutSystem {
            get {
                return ResourceManager.GetString("AboutSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Access.
        /// </summary>
        internal static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to data can be obtained only after authorization..
        /// </summary>
        internal static string AccessToDataCanBeObtainedOnlyAfterAuthorization {
            get {
                return ResourceManager.GetString("AccessToDataCanBeObtainedOnlyAfterAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Author.
        /// </summary>
        internal static string Add_Author {
            get {
                return ResourceManager.GetString("Add Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        internal static string Add_Book {
            get {
                return ResourceManager.GetString("Add Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Library Member.
        /// </summary>
        internal static string Add_Library_Member {
            get {
                return ResourceManager.GetString("Add Library Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Book.
        /// </summary>
        internal static string Add_New_Book {
            get {
                return ResourceManager.GetString("Add New Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string Add_User {
            get {
                return ResourceManager.GetString("Add User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string An_error_occurred_while_processing_your_request_ {
            get {
                return ResourceManager.GetString("An error occurred while processing your request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and restarting the app..
        /// </summary>
        internal static string and_restarting_the_app_ {
            get {
                return ResourceManager.GetString("and restarting the app.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string Authentication_failed {
            get {
                return ResourceManager.GetString("Authentication failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string AuthenticationFailedError {
            get {
                return ResourceManager.GetString("AuthenticationFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthorIsRequired.
        /// </summary>
        internal static string AuthorIsRequired {
            get {
                return ResourceManager.GetString("AuthorIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (The administrator can also give administration rights to other users).
        /// </summary>
        internal static string AuthorizationDescription {
            get {
                return ResourceManager.GetString("AuthorizationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name Is Required.
        /// </summary>
        internal static string AuthorNameIsRequired {
            get {
                return ResourceManager.GetString("AuthorNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available/Total.
        /// </summary>
        internal static string Available_Total {
            get {
                return ResourceManager.GetString("Available/Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to books.
        /// </summary>
        internal static string Back_to_books {
            get {
                return ResourceManager.GetString("Back to books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to members.
        /// </summary>
        internal static string Back_to_members {
            get {
                return ResourceManager.GetString("Back to members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book number is required.
        /// </summary>
        internal static string BookNumberIsRequired {
            get {
                return ResourceManager.GetString("BookNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of books should be between 1 and 30..
        /// </summary>
        internal static string BookNumberRange {
            get {
                return ResourceManager.GetString("BookNumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book title is required.
        /// </summary>
        internal static string BookTitleIsRequired {
            get {
                return ResourceManager.GetString("BookTitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book title should not exceed 100 characters.
        /// </summary>
        internal static string BookTitleShouldNotExceed100Characters {
            get {
                return ResourceManager.GetString("BookTitleShouldNotExceed100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Model.
        /// </summary>
        internal static string DataModel {
            get {
                return ResourceManager.GetString("DataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        internal static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        internal static string Development_Mode {
            get {
                return ResourceManager.GetString("Development Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees will be able to replace paper records with digital ones. Data about books, authors and readers will be stored in the database. The convenient and intuitive interface of this system will be an assistant in work and will significantly help to easily keep records and quickly find the necessary information..
        /// </summary>
        internal static string EmployeesRights {
            get {
                return ResourceManager.GetString("EmployeesRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment by setting the.
        /// </summary>
        internal static string environment_by_setting_the {
            get {
                return ResourceManager.GetString("environment by setting the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment variable to.
        /// </summary>
        internal static string environment_variable_to {
            get {
                return ResourceManager.GetString("environment variable to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment will display more detailed information about the error that occurred..
        /// </summary>
        internal static string environment_will_display_more_detailed_information_about_the_error_that_occurred_ {
            get {
                return ResourceManager.GetString("environment will display more detailed information about the error that occurred." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        internal static string Error_ {
            get {
                return ResourceManager.GetString("Error.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For local debugging, enable the.
        /// </summary>
        internal static string For_local_debugging__enable_the {
            get {
                return ResourceManager.GetString("For local debugging, enable the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Genre_Any {
            get {
                return ResourceManager.GetString("Genre_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime.
        /// </summary>
        internal static string Genre_Crime {
            get {
                return ResourceManager.GetString("Genre_Crime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical Fiction.
        /// </summary>
        internal static string Genre_HistoricalFiction {
            get {
                return ResourceManager.GetString("Genre_HistoricalFiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery.
        /// </summary>
        internal static string Genre_Mystery {
            get {
                return ResourceManager.GetString("Genre_Mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novel.
        /// </summary>
        internal static string Genre_Novel {
            get {
                return ResourceManager.GetString("Genre_Novel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Fiction.
        /// </summary>
        internal static string Genre_ScienceFiction {
            get {
                return ResourceManager.GetString("Genre_ScienceFiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre is required.
        /// </summary>
        internal static string GenreIsRequired {
            get {
                return ResourceManager.GetString("GenreIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information System &quot;Library&quot;.
        /// </summary>
        internal static string InformationSystemLibrary {
            get {
                return ResourceManager.GetString("InformationSystemLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances.
        /// </summary>
        internal static string Instances {
            get {
                return ResourceManager.GetString("Instances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances Count.
        /// </summary>
        internal static string Instances_Count {
            get {
                return ResourceManager.GetString("Instances Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN is required.
        /// </summary>
        internal static string ISBNisRequired {
            get {
                return ResourceManager.GetString("ISBNisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can result in displaying sensitive information from exceptions to end users..
        /// </summary>
        internal static string It_can_result_in_displaying_sensitive_information_from_exceptions_to_end_users_ {
            get {
                return ResourceManager.GetString("It can result in displaying sensitive information from exceptions to end users.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend.
        /// </summary>
        internal static string Lend {
            get {
                return ResourceManager.GetString("Lend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend Book.
        /// </summary>
        internal static string Lend_Book {
            get {
                return ResourceManager.GetString("Lend Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name Is Required.
        /// </summary>
        internal static string LoginNameIsRequired {
            get {
                return ResourceManager.GetString("LoginNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Book.
        /// </summary>
        internal static string Manage_Book {
            get {
                return ResourceManager.GetString("Manage Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name Is Required.
        /// </summary>
        internal static string MemberNameIsRequired {
            get {
                return ResourceManager.GetString("MemberNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Is Required.
        /// </summary>
        internal static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Is Required.
        /// </summary>
        internal static string PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number should be in format +380#########.
        /// </summary>
        internal static string PhoneNumberShouldBeInFormat {
            get {
                return ResourceManager.GetString("PhoneNumberShouldBeInFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project was created to automate the work of the library..
        /// </summary>
        internal static string ProjectGoal {
            get {
                return ResourceManager.GetString("ProjectGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Info.
        /// </summary>
        internal static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish year should be between 1800 and 2024.
        /// </summary>
        internal static string PublishYearShouldBeBetween1800and2024 {
            get {
                return ResourceManager.GetString("PublishYearShouldBeBetween1800and2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A system administrator can register a new user. If you do not have a login and password, contact the administrator..
        /// </summary>
        internal static string RegistrationInfo {
            get {
                return ResourceManager.GetString("RegistrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        internal static string Repeat_Password {
            get {
                return ResourceManager.GetString("Repeat Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID:.
        /// </summary>
        internal static string Request_ID_ {
            get {
                return ResourceManager.GetString("Request ID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is required.
        /// </summary>
        internal static string RoleIsRequired {
            get {
                return ResourceManager.GetString("RoleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Fiction.
        /// </summary>
        internal static string Science_Fiction {
            get {
                return ResourceManager.GetString("Science Fiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a member.
        /// </summary>
        internal static string Select_a_member {
            get {
                return ResourceManager.GetString("Select a member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select genre.
        /// </summary>
        internal static string Select_genre {
            get {
                return ResourceManager.GetString("Select genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select genre....
        /// </summary>
        internal static string Select_genre___ {
            get {
                return ResourceManager.GetString("Select genre...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swapping to.
        /// </summary>
        internal static string Swapping_to {
            get {
                return ResourceManager.GetString("Swapping to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken Books.
        /// </summary>
        internal static string Taken_Books {
            get {
                return ResourceManager.GetString("Taken Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken by.
        /// </summary>
        internal static string Taken_by {
            get {
                return ResourceManager.GetString("Taken by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Development environment shouldn&apos;t be enabled for deployed applications..
        /// </summary>
        internal static string The_Development_environment_shouldn_t_be_enabled_for_deployed_applications_ {
            get {
                return ResourceManager.GetString("The Development environment shouldn\'t be enabled for deployed applications.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format should ISBN 10 or 13.
        /// </summary>
        internal static string TheFormatShouldISBN10or13 {
            get {
                return ResourceManager.GetString("TheFormatShouldISBN10or13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name here....
        /// </summary>
        internal static string Type_name_here___ {
            get {
                return ResourceManager.GetString("Type name here...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user..
        /// </summary>
        internal static string UnknownUserError {
            get {
                return ResourceManager.GetString("UnknownUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Author.
        /// </summary>
        internal static string Update_Author {
            get {
                return ResourceManager.GetString("Update Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Book.
        /// </summary>
        internal static string Update_Book {
            get {
                return ResourceManager.GetString("Update Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Member.
        /// </summary>
        internal static string Update_Member {
            get {
                return ResourceManager.GetString("Update Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        internal static string Update_User {
            get {
                return ResourceManager.GetString("Update User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        internal static string User_Details {
            get {
                return ResourceManager.GetString("User Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Is Required..
        /// </summary>
        internal static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have insufficient privileges to access this page..
        /// </summary>
        internal static string You_have_insufficient_privileges_to_access_this_page_ {
            get {
                return ResourceManager.GetString("You have insufficient privileges to access this page.", resourceCulture);
            }
        }
    }
}
